### PR TITLE
Update Alpine packages whenever REFRESHED_AT is changed in Dockerfile

### PR DESCRIPTION
**Pull request by mikesager**
This keeps the underlying Alpine packages up-to-date.

### CODE REVIEW

**Comment by SISheogorath** [comment]
Doesn't sound very nice to me. In this case we should rebuild the container.

The updates inside the containers create a bigger delta which harms the read/write performance of the image.

**Comment by mikesager** [comment]
I haven't really discovered if there's a best-practice way to do this yet.  Do we know for certain if the upstream alpine base image is kept up-to-date, such that a rebuild will pull in the latest security fixes?

**Comment by SISheogorath** [comment]
You can easily check the latest build: https://hub.docker.com/r/library/alpine/tags/

Currently there is another problem: The image is not automatically build on alpine builds. But that's more a lag of configuration of the docker hub build than it is a issues that should fixed by containerside patches.

Containers should be as stateless as possible. And updating a container is a task you will redo all the time and harm your performance while you can easily rebuild the image to have the same up-to-date state like you have when you upgrade the container on startup. If you want to make sure to always have the latest binary in your image it's better to configure a cron job or systemd.timer to rebuild your image than do patching on startup.

**Comment by mikesager** [comment]
Oh, okay.  I think we're actually pretty close to on the same page if I'm hearing you right.  This commit only updates on rebuild, not on container startup.  That said, it does look like we're due for the 3.5 update, which I see you have submitted the PR for.  Thanks!

**Comment by bddenhartog** [comment]
In thinking more about this (from our conversation on your fork, @mikesager), I agree with @SISheogorath here. Thanks anyway!

**Pull request closed without merging**
